baseURL = "https://ermolov.dev/"
# include content marked as draft
buildDrafts = false
# include content with publishdate in the future
buildFuture = false
# include content already expired
buildExpired = false
# enable this to make all relative URLs relative to content root. Note that this does not affect absolute URLs.
relativeURLs = true
disableRSS = true
enableRobotsTXT = true
editor = "nano"
languageCode = "en"
language = "en"
theme = "vncnt-hugo"
title = "Viktor Ermolov Â· Landing Page"

[permalinks]
  fixed = ":title/"
  posts = "posts/:slug/"

[params]
  author = "Viktor Ermolov"
  # email does still work but is deprecated.
  # use [params.contact.email] instead.
  #email = "john.doe@example.com"
  description = "Landing Page"
  bio = "Freelance Software Developer.  \nPython | Django | Flask | FastAPI | JavaScript | SQL | NoSQL | HTML | CSS | RESTful API | Docker | CI/CD | GIT"
  avatar = "img/avatar.jpg"
  favicon = "img/favicon.ico"
  error404 = "There is no such page."

  [params.contact]
    github = "https://github.com/Bytlot"
    # instagram = "https://instagram.com/jdoe"
    twitter = "https://twitter.com/VikErmolov"
    linkedin = "https://www.linkedin.com/in/vermolov/"
    # You may use (inline) tables for more versatility
    # This allows sorting and even more icons.
    # Just make sure not to mix key-value pairs, inline tables and tables,
    # although keeping keeping this order is ok.
    # See https://toml.io/en/v1.0.0 for details
    # 0 = { name = "ello", icon = "ello", style = "fab", link = "" } # empty links are relative to site root
  
    [params.contact.email]
      name = "email" # may be omitted. defaults to key name
      icon = "envelope" # may be omitted. defaults to key name
      style = "fas" # may be omitted. default = "fas"
      link = "mailto:viktor@ermolov.dev"
      
